### PR TITLE
Updated explorer docs with new routes

### PR DESCRIPTION
**Pull request by 3C111**

### CODE REVIEW

**Comment by jirikuncar** [comment]
@3C111 please try to build the documentation locally before creating a PR.

See the error from travis:
```
/home/travis/build/SwissDataScienceCenter/renga-documentation/docs/developer/explorer_service.rst:91:Definition list ends without a blank line; unexpected unindent.
```

**Comment by 3C111** [comment]
Sure, it just doesn't work out of the box.

**Comment by jirikuncar** [comment]
@3C111 what doesn't work? There is a requirements file in docs folder. The rest is shown in `.travis.yml`.

**Comment by jirikuncar** [comment]
I am curious what did you have to change since the build is working on travis.

**Comment by 3C111** [comment]
When making the html file I got the error:" Extension error: 
Could not import extension sphinx.ext.githubpages (exception: No module named githubpages)"  

This was solved by removing the "sphinx.ext.githubpage" tag from the conf.py file. 

This might be because I didn't follow the travis file for the dependencies since I believe I might have cloned the project before the travis file was added.

**Pull request merged**
